# Generated by Django 3.2.5 on 2021-07-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservahospedagem',
            name='data_reserva',
            field=models.DateField(null=True),
        ),
    ]
